import { StateData } from '@/types';

export const statesData: Record<string, StateData> = {
  'AL': {
    stateCode: 'AL',
    stateName: 'Alabama',
    voterIdRequired: true,
    voterIdType: 'strict-photo',
    automaticVoterRegistration: false,
    sameDayRegistration: false,
    earlyVotingDays: 0,
    noExcuseAbsentee: false,
    felonyDisenfranchisement: 'post-sentence',
    onlineRegistration: true,
    preRegistrationAge: 18,
    registrationDeadlineDays: 15,
    lastElectionTurnout: 61.8,
    electoralVotes: 9,
    governorParty: 'R',
    legislatureControl: 'R',
  },
  'AK': {
    stateCode: 'AK',
    stateName: 'Alaska',
    voterIdRequired: true,
    voterIdType: 'non-strict-photo',
    automaticVoterRegistration: true,
    sameDayRegistration: false,
    earlyVotingDays: 15,
    noExcuseAbsentee: true,
    felonyDisenfranchisement: 'parole',
    onlineRegistration: true,
    preRegistrationAge: 18,
    registrationDeadlineDays: 30,
    lastElectionTurnout: 61.0,
    electoralVotes: 3,
    governorParty: 'R',
    legislatureControl: 'Split',
  },
  'AZ': {
    stateCode: 'AZ',
    stateName: 'Arizona',
    voterIdRequired: true,
    voterIdType: 'strict-photo',
    automaticVoterRegistration: false,
    sameDayRegistration: false,
    earlyVotingDays: 27,
    noExcuseAbsentee: true,
    felonyDisenfranchisement: 'post-sentence',
    onlineRegistration: true,
    preRegistrationAge: 18,
    registrationDeadlineDays: 29,
    lastElectionTurnout: 65.9,
    electoralVotes: 11,
    governorParty: 'D',
    legislatureControl: 'R',
  },
  'CA': {
    stateCode: 'CA',
    stateName: 'California',
    voterIdRequired: false,
    voterIdType: 'none',
    automaticVoterRegistration: true,
    sameDayRegistration: true,
    earlyVotingDays: 29,
    noExcuseAbsentee: true,
    felonyDisenfranchisement: 'none',
    onlineRegistration: true,
    preRegistrationAge: 16,
    registrationDeadlineDays: 15,
    lastElectionTurnout: 70.8,
    electoralVotes: 54,
    governorParty: 'D',
    legislatureControl: 'D',
  },
  'NY': {
    stateCode: 'NY',
    stateName: 'New York',
    voterIdRequired: false,
    voterIdType: 'none',
    automaticVoterRegistration: true,
    sameDayRegistration: false,
    earlyVotingDays: 10,
    noExcuseAbsentee: false,
    felonyDisenfranchisement: 'none',
    onlineRegistration: true,
    preRegistrationAge: 16,
    registrationDeadlineDays: 10,
    lastElectionTurnout: 63.6,
    electoralVotes: 28,
    governorParty: 'D',
    legislatureControl: 'D',
  },
  'TX': {
    stateCode: 'TX',
    stateName: 'Texas',
    voterIdRequired: true,
    voterIdType: 'strict-photo',
    automaticVoterRegistration: false,
    sameDayRegistration: false,
    earlyVotingDays: 17,
    noExcuseAbsentee: false,
    felonyDisenfranchisement: 'parole',
    onlineRegistration: false,
    preRegistrationAge: 17,
    registrationDeadlineDays: 30,
    lastElectionTurnout: 60.2,
    electoralVotes: 40,
    governorParty: 'R',
    legislatureControl: 'R',
  },
  'FL': {
    stateCode: 'FL',
    stateName: 'Florida',
    voterIdRequired: true,
    voterIdType: 'non-strict-photo',
    automaticVoterRegistration: false,
    sameDayRegistration: false,
    earlyVotingDays: 10,
    noExcuseAbsentee: true,
    felonyDisenfranchisement: 'post-sentence',
    onlineRegistration: true,
    preRegistrationAge: 16,
    registrationDeadlineDays: 29,
    lastElectionTurnout: 71.7,
    electoralVotes: 30,
    governorParty: 'R',
    legislatureControl: 'R',
  },
  'GA': {
    stateCode: 'GA',
    stateName: 'Georgia',
    voterIdRequired: true,
    voterIdType: 'strict-photo',
    automaticVoterRegistration: true,
    sameDayRegistration: false,
    earlyVotingDays: 17,
    noExcuseAbsentee: true,
    felonyDisenfranchisement: 'parole',
    onlineRegistration: true,
    preRegistrationAge: 17,
    registrationDeadlineDays: 28,
    lastElectionTurnout: 67.7,
    electoralVotes: 16,
    governorParty: 'R',
    legislatureControl: 'R',
  },
  'PA': {
    stateCode: 'PA',
    stateName: 'Pennsylvania',
    voterIdRequired: false,
    voterIdType: 'none',
    automaticVoterRegistration: true,
    sameDayRegistration: false,
    earlyVotingDays: 0,
    noExcuseAbsentee: true,
    felonyDisenfranchisement: 'none',
    onlineRegistration: true,
    preRegistrationAge: 18,
    registrationDeadlineDays: 15,
    lastElectionTurnout: 70.9,
    electoralVotes: 19,
    governorParty: 'D',
    legislatureControl: 'Split',
  },
  'WI': {
    stateCode: 'WI',
    stateName: 'Wisconsin',
    voterIdRequired: true,
    voterIdType: 'strict-photo',
    automaticVoterRegistration: false,
    sameDayRegistration: true,
    earlyVotingDays: 14,
    noExcuseAbsentee: true,
    felonyDisenfranchisement: 'parole',
    onlineRegistration: true,
    preRegistrationAge: 18,
    registrationDeadlineDays: 20,
    lastElectionTurnout: 75.8,
    electoralVotes: 10,
    governorParty: 'D',
    legislatureControl: 'R',
  },
  'MI': {
    stateCode: 'MI',
    stateName: 'Michigan',
    voterIdRequired: true,
    voterIdType: 'non-strict-photo',
    automaticVoterRegistration: true,
    sameDayRegistration: true,
    earlyVotingDays: 9,
    noExcuseAbsentee: true,
    felonyDisenfranchisement: 'none',
    onlineRegistration: true,
    preRegistrationAge: 16,
    registrationDeadlineDays: 15,
    lastElectionTurnout: 73.9,
    electoralVotes: 15,
    governorParty: 'D',
    legislatureControl: 'D',
  },
  'IL': {
    stateCode: 'IL',
    stateName: 'Illinois',
    voterIdRequired: false,
    voterIdType: 'none',
    automaticVoterRegistration: true,
    sameDayRegistration: true,
    earlyVotingDays: 40,
    noExcuseAbsentee: true,
    felonyDisenfranchisement: 'none',
    onlineRegistration: true,
    preRegistrationAge: 16,
    registrationDeadlineDays: 28,
    lastElectionTurnout: 70.1,
    electoralVotes: 19,
    governorParty: 'D',
    legislatureControl: 'D',
  },
  'OH': {
    stateCode: 'OH',
    stateName: 'Ohio',
    voterIdRequired: true,
    voterIdType: 'strict-photo',
    automaticVoterRegistration: false,
    sameDayRegistration: false,
    earlyVotingDays: 28,
    noExcuseAbsentee: true,
    felonyDisenfranchisement: 'none',
    onlineRegistration: true,
    preRegistrationAge: 17,
    registrationDeadlineDays: 30,
    lastElectionTurnout: 66.7,
    electoralVotes: 17,
    governorParty: 'R',
    legislatureControl: 'R',
  },
  'NC': {
    stateCode: 'NC',
    stateName: 'North Carolina',
    voterIdRequired: true,
    voterIdType: 'strict-photo',
    automaticVoterRegistration: false,
    sameDayRegistration: true,
    earlyVotingDays: 17,
    noExcuseAbsentee: true,
    felonyDisenfranchisement: 'none',
    onlineRegistration: true,
    preRegistrationAge: 16,
    registrationDeadlineDays: 25,
    lastElectionTurnout: 75.4,
    electoralVotes: 16,
    governorParty: 'D',
    legislatureControl: 'R',
  },
  // Adding placeholders for others to ensure the map works
};

// Fill in the rest with default/placeholder data for a complete map
const allStateCodes = ['AR', 'CO', 'CT', 'DE', 'HI', 'ID', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'ND', 'OK', 'OR', 'RI', 'SC', 'SD', 'TN', 'UT', 'VT', 'VA', 'WA', 'WV', 'WY', 'DC'];

allStateCodes.forEach(code => {
  if (!statesData[code]) {
    statesData[code] = {
      stateCode: code,
      stateName: code, // Placeholder
      voterIdRequired: false,
      voterIdType: 'none',
      automaticVoterRegistration: true,
      sameDayRegistration: true,
      earlyVotingDays: 15,
      noExcuseAbsentee: true,
      felonyDisenfranchisement: 'none',
      onlineRegistration: true,
      preRegistrationAge: 18,
      registrationDeadlineDays: 15,
      lastElectionTurnout: 65.0,
      electoralVotes: 3,
      governorParty: 'I',
      legislatureControl: 'Split',
    };
  }
});
